"""
config.py — NickOS runtime configuration & path resolver.

┌─────────────────────────────────────────────────────────────┐
│  Local dev:   paths relative to repo root                   │
│               token JSON files read from gmail/tokens/      │
│  Production:  DATA_DIR=/data (Railway persistent volume)    │
│               token files decoded from base64 env vars      │
│               and materialized to /tmp/nickos_tokens/       │
└─────────────────────────────────────────────────────────────┘

Token env vars to set in Railway (generated by deploy.sh):
  GMAIL_CREDENTIALS_B64   ← base64(gmail/credentials.json)
  GMAIL_TOKEN_1_B64       ← base64(gmail/tokens/account1_token.json)
  GMAIL_TOKEN_2_B64       ← base64(gmail/tokens/account2_token.json)
  GMAIL_TOKEN_3_B64       ← base64(gmail/tokens/account3_token.json)
  CALENDAR_TOKEN_B64      ← base64(gmail/tokens/calendar_token.json)

Usage:
    from config import MEMORY_FILE, DAILY_LOGS, DB_PATH, TOKENS_DIR
"""

import os
import sys
import base64
import json
from pathlib import Path
from dotenv import load_dotenv

ROOT = Path(__file__).parent
load_dotenv(ROOT / ".env", override=False)  # don't override real env vars in prod

# ── Environment detection ─────────────────────────────────────────────────────
# Railway injects RAILWAY_ENVIRONMENT; DATA_DIR set manually for other prod hosts
IS_PROD = bool(
    os.environ.get("RAILWAY_ENVIRONMENT")
    or os.environ.get("DATA_DIR")
    or os.environ.get("IS_PROD")
)

# ── Persistent data directory ─────────────────────────────────────────────────
# Railway: mount a volume at /data (persists across deploys)
# Local:   repo root (same as before)
DATA_DIR = Path(os.environ.get("DATA_DIR", ROOT))

MEMORY_DIR  = DATA_DIR / "memory"
DAILY_LOGS  = MEMORY_DIR / "daily_logs"
MEMORY_FILE = MEMORY_DIR / "MEMORY.md"
DB_PATH     = DATA_DIR / "db" / "nickos.db"

# Ensure directories exist
DAILY_LOGS.mkdir(parents=True, exist_ok=True)
(DATA_DIR / "db").mkdir(parents=True, exist_ok=True)

# ── Gmail token paths ─────────────────────────────────────────────────────────
# Local dev:  read from git-ignored gmail/tokens/*.json
# Production: materialized into /tmp/nickos_tokens/ from base64 env vars
TOKENS_DIR: Path = (
    Path("/tmp/nickos_tokens") if IS_PROD
    else (ROOT / "gmail" / "tokens")
)

CREDENTIALS_PATH: Path = (
    TOKENS_DIR / "credentials.json" if IS_PROD
    else Path(os.environ.get("GMAIL_CREDENTIALS_PATH", str(ROOT / "gmail" / "credentials.json")))
)

CALENDAR_TOKEN_PATH: Path = TOKENS_DIR / "calendar_token.json"

# ── Token materialization ─────────────────────────────────────────────────────

_TOKEN_MAP: dict[str, str] = {
    "credentials.json":    "GMAIL_CREDENTIALS_B64",
    "account1_token.json": "GMAIL_TOKEN_1_B64",
    "account2_token.json": "GMAIL_TOKEN_2_B64",
    "account3_token.json": "GMAIL_TOKEN_3_B64",
    "calendar_token.json": "CALENDAR_TOKEN_B64",
}


def materialize_tokens() -> list[str]:
    """
    Decode base64 env vars → write JSON token files to TOKENS_DIR.
    Returns list of missing env var names (empty = all good).
    No-op in local dev (IS_PROD=False).
    """
    if not IS_PROD:
        return []

    TOKENS_DIR.mkdir(parents=True, exist_ok=True)
    missing: list[str] = []

    for filename, env_var in _TOKEN_MAP.items():
        dest = TOKENS_DIR / filename
        if dest.exists():
            continue  # already materialized this process lifetime

        val = os.environ.get(env_var, "").strip()
        if not val:
            missing.append(env_var)
            continue

        try:
            decoded = base64.b64decode(val).decode("utf-8")
            json.loads(decoded)          # validate JSON before writing
            dest.write_text(decoded)
        except Exception as e:
            print(f"[config] ⚠ Failed to decode {env_var}: {e}", file=sys.stderr)
            missing.append(env_var)

    return missing


# Bootstrap MEMORY.md in prod if it doesn't exist yet
def _init_memory() -> None:
    if MEMORY_FILE.exists():
        return
    MEMORY_DIR.mkdir(parents=True, exist_ok=True)
    starter = os.environ.get("MEMORY_MD_B64", "")
    if starter:
        try:
            MEMORY_FILE.write_text(base64.b64decode(starter).decode("utf-8"))
            print("[config] ✓ MEMORY.md restored from env var", file=sys.stderr)
            return
        except Exception:
            pass
    # Create a minimal starter file
    MEMORY_FILE.write_text(
        "# Nick's Memory\n\n"
        "## Today's Focus\n\nNot yet set\n\n"
        "## Active Goals\n\n"
        "## Recent Wins 🏆\n\n"
        "## Health Tracking\n\n"
        "- Current streak: 0\n"
        "- Meals today: 0/3\n"
        "- This week: 0/5\n"
        "- Last logged sleep: `—`\n"
    )
    print("[config] ✓ Created starter MEMORY.md", file=sys.stderr)


# Run materialisation on import
_missing = materialize_tokens()
_init_memory()

if _missing and IS_PROD:
    print(
        f"[config] ⚠ Missing token env vars: {', '.join(_missing)}\n"
        "  Run deploy.sh locally to generate the base64 values.",
        file=sys.stderr,
    )
